# Generated by Django 5.1.6 on 2025-02-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('In', 'Indian'), ('CH', 'Chinese'), ('ET', 'Ethiopia'), ('OT', 'Other')], default='', max_length=3),
            preserve_default=False,
        ),
    ]
